services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "${DB_PORT}"
    volumes:
      - my-db:/var/lib/postgresql/data
volumes:
  my-db:
